name: Refresh ELO Rankings

on:
  push:
    branches:
      - Liam_Webscraper
  workflow_dispatch:

jobs:
  refresh_rankings:
    runs-on: ubuntu-latest
    name: "Rankings refresh triggered by ${{ github.event.inputs.user }} on ${{ github.event.inputs.date }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

    #   - name: Set up R
        # uses: r-lib/actions/setup-r@v2

    #   - name: Setup dependencies
    #     uses: r-lib/actions/setup-r-dependencies@v2
    #     with:
    #       cache-version: 2

    #   - name: Cache R packages
    #     uses: actions/cache@v2
    #     with:
    #       path: ${{ env.R_LIBS_USER }}
    #       key: ${{ runner.os }}-R-${{ hashFiles('**/DESCRIPTION') }}

      - name: Install Python Packages
        run: |
          pip install selenium
          pip install numpy>=1.20.3
          pip install pandas

      - name: Scrape Data from Fwango
        run: python Scripts/scrape_fwango_data.py

      - name: Find downloaded files
        run: |
          pwd
          ls -la /
          ls -la /home
          ls -la /home/runner
          ls -la /home/runner/work
          ls -la /home/runner/work/rankings_model
          ls -la
        # mv "* - Match results*" "Tourney Results/Manual Downloads/Testing/"

      - name: Convert Results into Correct Format
        run: echo "Rscript Scripts/results_converter.R"

      - name: Run Rankings Model & Generate New Rankings
        run: echo 'Rscript "Scripts/fit_models_1v2.R"'

      - name: Stage Changes
        run: echo "git add Tourney\ Results/Manual\ Downloads/*"

      - name: Commit and Push results
        run: |
          echo "Don't commit anything here for now"
          echo "This is just for testing"
        #   git config --local user.email '${{ github.actor }}@users.noreply.github.com'
        #   git config --local user.name '${{ github.actor }}'
        #   commit_message="Testing Scraping and Rankings refresh on $(date +"%Y-%m-%d")"
        #   git commit -m "$commit_message" || echo "No changes to commit"
        #   git push origin || echo "No changes to commit"