name: Test ELO

on:
    push:
        branches:
          - main
          - Jake_ELO
    workflow_dispatch:

jobs:
  refresh_rankings:
    runs-on: ubuntu-latest
    name: "Rankings refresh triggered by ${{ github.event.inputs.user }} on ${{ github.event.inputs.date }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Update ELO 
        run: python src/dags/run_elo.py

      - name: Verify Changes
        run: |
          ls -la data
          git status

      - name: Stage Changes
        run: git add data/*

      - name: Commit and Push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email '${{ github.actor }}@users.noreply.github.com'
          git config --local user.name '${{ github.actor }}'
          commit_message="ELO Correct   on $(date +"%Y-%m-%d")"
          git commit -m "$commit_message" || echo "No changes to commit"
          git push origin || echo "No changes to commit"


